language: go
go: 1.11.2

services:
  - docker

branches:
  only:
    - master

before_script:
  - export GOROOT=${TRAVIS_HOME}/gopath/src/github.com/gleb-kosteiko/godis_server
  
script:
  - go clean && go test ./... -coverprofile coverage.out && go build
  - docker build -t godis_server .
  - docker run --rm -p 9090:9090 godis_server

notifications:
  email:
    on_success: never
    on_failure: always
